name: 🧪

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: The Guestbook
        uses: joshmgross/guestbook@v1.0.3
        with:
          issue: 1
          approvers: |
            pborlongan
          guestbook-path: README.md
# from: https://github.com/marketplace/actions/the-guestbook
